###############################################################################
# xxxxx : portfolio project for macOS

# author    - Michael Treanor  <skeptycal@gmail.com>
# copyright - 2019 (c) Michael Treanor
# license   - MIT <https://opensource.org/licenses/MIT>
# github    - https://www.github.com/skeptycal
###############################################################################
# Pre-commit Sample yaml template
# default_language_version:
# python: python3.7
default_stages: [commit, push]
exclude: "^$"
fail_fast: false

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: git://github.com/dnephin/pre-commit-golang
      rev: master
      hooks:
          - id: go-fmt
          - id: go-vet
          - id: go-lint
          - id: go-imports
          - id: go-cyclo
            args: [-over=15]
          - id: validate-toml
          - id: no-go-testing
          - id: gometalinter
          - id: golangci-lint
          - id: go-critic
          - id: go-unit-tests
          - id: go-build
          - id: go-mod-tidy

      # @see http://pre-commit.com/
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: check-yaml
            files: \.(yaml|yml)$
          - id: check-added-large-files
          - id: check-byte-order-marker
          - id: check-docstring-first
          - id: check-case-conflict
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          #   -   id: detect-aws-credentials
          - id: detect-private-key
          - id: end-of-file-fixer
          # - id: flake8
          #   args: [--max-line-length=79]
          # - id: pretty-format-json
          - id: requirements-txt-fixer
          - id: trailing-whitespace
      # pylint settings ... replace as needed
    # - repo: git://github.com/pre-commit/mirrors-pylint
    #   sha: master
    #   hooks:
    #       - id: pylint
