language: go
sudo: false
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  # irc:
  #   channels: "irc.freenode.org#xxxxx"
  #   template:
  #     - "%{repository_name}@%{branch}: %{message} (%{build_url})"
  #   on_success: change
  #   on_failure: change
  email: skeptycal@gmail.com
